### ISSUE TITLE
Netlist generation for synopsys primetime

### ISSUE THREAD

**Issue by f2013619** [pulp-platform/pulpino#120] opened 2017-10-12 15:58 UTC
Hi,
I want to do power analysis of the application that i implemented in pulpino using synopsys prime time. Can you help me with how I can generate the netlist file for pulpino?

**Comment by FrancescoConti** [comment] 2017-10-12 16:06
This is a duplicate of issue #114 . From our comments there:
> If you are wondering why we don't distribute memory macros but just a placeholder, there's basically two reasons: first, our distribution is technology-agnostic (at least for what concerns RTL); second, and most important, we cannot distribute memory functional models or macros from real-world foundries as they are not ours. We typically access them under non-disclosure agreements.

and

> We include all the necessary instructions for RTL simulation in the README.md file. We do not provide any synthesis script for the reasons I stated before; you can probably reuse many of our RTL scripts but you will have to set up the simulation platform on your own if you want to perform post-synthesis or post-layout simulation on a gate-level netlist.

In other words, we do not provide scripts to synthesize PULPino. Good starting point to develop your own are 1) the RTL simulation scripts, 2) the FPGA synthesis scripts.

**Closed by FrancescoConti** 2017-10-12 16:06 UTC
