### ISSUE TITLE
vcompile_ips.csh: No such file or directory

### ISSUE THREAD

**Issue by rajatssr835** [pulp-platform/pulpino#169] opened 2018-02-13 09:48 UTC
Hi I am getting the following issue while running "make vcompile" command:

--> Compiling PULPino Platform...

/home/urbi/pulpino-master/vsim/..//vsim/vcompile/vcompile_ips.csh: No such file or directory.
make[3]: *** [CMakeFiles/vcompile] Error 1
make[2]: *** [CMakeFiles/vcompile.dir/all] Error 2
make[1]: *** [CMakeFiles/vcompile.dir/rule] Error 2
make: *** [vcompile] Error 2

**Comment by zarubaf** [comment] 2018-02-13 10:10
Did you run `./update-ips/py`. Also have a look at the closed issues. There are literally tens of similar issues.

**Comment by zarubaf** [comment] 2018-02-13 10:14
Duplicate of #13

**Closed by zarubaf** 2018-02-13 10:14 UTC
