### ISSUE TITLE
branch taken bit

### ISSUE THREAD

**Issue by LilachDery** [pulp-platform/pulpino#199] opened 2018-04-30 16:53 UTC
Hi,
I am working on create a data base of branch commands from trace_core_00_0.log which is the output of "hello world.v" and I am searching after the 'BRANCH_TAKEN' bit. where do I find it? 
I want that the model_sim will show and output that bit ('BRANCH_TAKEN') after executing the code of "hello world".

Do you have a seggestions for doing that?
Thanks,

**Comment by FrancescoConti** [comment] 2018-04-30 17:07
Closed as duplicate of #200

**Closed by FrancescoConti** 2018-04-30 17:07 UTC
